---
title: "logo"
author: "Kelly L. Sovacool"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{logo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cowplot)
library(here)
library(hexSticker)
library(showtext)

# Loading Google fonts (http://www.google.com/fonts)
font_add_google("Source Sans Pro", "Source Sans Pro", regular.wt = 400, bold.wt = 600)
showtext_auto()
```

## Emojis

From OpenMoji, [licensed under CC BY SA 4.0](https://github.com/hfg-gmuend/openmoji/blob/master/LICENSE.txt)

- poop: https://openmoji.org/library/#search=poo&emoji=1F4A9
- wrench: https://openmoji.org/library/#search=tool&emoji=1F527
- hammer: https://openmoji.org/library/#search=tool&emoji=1F528

```{r logo, dpi=300}
poo_file <- here('vignettes', 'articles','1F4A9_color.png')
wrench_file <- here('vignettes', 'articles', '1F527_color.png')
hammer_file <- here('vignettes', 'articles', '1F528_color.png')
img <- ggdraw() +
    #draw_image(wrench_file, scale = 0.55, x = 0.195, y = 0.05) +
    draw_image(hammer_file, scale = 0.7, x = -0.32, y = 0.05) +
    draw_image(poo_file) 
ggsave2(img, 
        filename = here('vignettes', 'articles', 'poo-hammer.png'),
        height = 2,
        width = 2,
        units = 'in')

mint <- '#CBF3F0'
pink <- '#FA9DC5'
orange <- '#FFDBAD'
black <- '#000000'

sticker(img, package = 'schtools', 
        s_x = 1, s_y = 0.85, s_width = 1.6, s_height = 1.6,
        p_x = 1, p_y = 1.55, p_color = black, 
        p_size = 23, p_family = 'Source Sans Pro', 
        h_fill = mint, h_color = orange,
        url = 'schlosslab.org/schtools', u_size = 2.5,
        filename = here('vignettes', 'articles', 'schools-logo.png'))
```

